name: nekonata_reporter
description: "A new Flutter package project."
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  firebase_analytics: ^12.0.1
  firebase_crashlytics: ^5.0.1
  flutter:
    sdk: flutter
