name: nekonata_firestore
description: "Firestore wrapper for nekonata"
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_cloud_firestore: ^4.0.0
  mockito: ^5.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: false
