name: nekonata_firestore
description: "Firestore wrapper for nekonata"
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_cloud_firestore: ^4.0.0
