name: nekonata_service
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

resolution: workspace

dev_dependencies:
  test:
  very_good_analysis: ^7.0.0
